//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras_Detalhes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compras_Detalhes()
        {
            this.Compras = new HashSet<Compras>();
        }
    
        public int IDCompra_Detalhes { get; set; }
        public int Cliente { get; set; }
        public System.DateTime DataCompra { get; set; }
        public int Endereco { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compras> Compras { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual Enderecos Enderecos { get; set; }
    }
}
