//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public int IDCompras { get; set; }
        public int Produto { get; set; }
        public int Quantidade { get; set; }
        public int Detalhes { get; set; }
    
        public virtual Compras_Detalhes Compras_Detalhes { get; set; }
        public virtual Produtos Produtos { get; set; }
    }
}
