//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginMVC2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web.Mvc;
    using System.ComponentModel.DataAnnotations;

    public partial class Enderecos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enderecos()
        {
            this.Compras_Detalhes = new HashSet<Compras_Detalhes>();
        }

        public int IDEndereco { get; set; }
        public string Primeiro_Nome { get; set; }
        public string Sobrenome { get; set; }
        public string CEP { get; set; }
        public string Endereco { get; set; }
        public int Numero { get; set; }
        public string Complemento { get; set; }
        public int Estado { get; set; }
        public int Cidade { get; set; }
        public string Telefone { get; set; }
        public int Cliente { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compras_Detalhes> Compras_Detalhes { get; set; }
        public virtual Municipio Municipio { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual Estado Estado1 { get; set; }
    }

    public class Enderecos_Lista
    {
        public int EnderecoSelecionado { get; set; }

        public List<Enderecos> ListaEnderecos { get; set; }
    }

    [MetadataType(typeof(EnderecoMetadado))]
    public partial class Enderecos
    {
    }

    public class EnderecoMetadado
    {
        [DisplayName("Nome")]
        [Required(ErrorMessage = "Obrigatório informar o nome")]
        [TamanhoString(50)]
        public string Primeiro_Nome { get; set; }

        [DisplayName("CEP")]
        [Required(ErrorMessage = "Obrigatório informar o CEP")]
        [TamanhoString(12)]
        public string CEP { get; set; }

        [DisplayName("Sobrenome")]
        [Required(ErrorMessage = "Obrigatório informar o sobrenome")]
        [TamanhoString(50)]
        public string Sobrenome { get; set; }

        [DisplayName("Endereço")]
        [Required(ErrorMessage = "Obrigatório informar o endereço")]
        [TamanhoString(70)]
        public string Endereco { get; set; }

        [DisplayName("Número")]
        [Required(ErrorMessage = "Obrigatório informar o número")]
        public int Numero { get; set; }

        [DisplayName("Complemento")]
        [Required(ErrorMessage = "Obrigatório informar o complemento")]
        [TamanhoString(70)]
        public string Complemento { get; set; }

        [DisplayName("Estado")]
        [Required(ErrorMessage = "Obrigatório informar o estado")]
        public int Estado { get; set; }

        [DisplayName("Cidade")]
        [Required(ErrorMessage = "Obrigatório informar a cidade")]
        public int Cidade { get; set; }

        [DisplayName("Telefone")]
        [Required(ErrorMessage = "Obrigatório informar o telefone")]
        [TamanhoString(15)]
        public string Telefone { get; set; }
    }
}
