//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginMVC2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntidadeLojasFelipe : DbContext
    {
        public EntidadeLojasFelipe()
            : base("name=EntidadeLojasFelipe")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carrinho> Carrinho { get; set; }
        public virtual DbSet<Compras> Compras { get; set; }
        public virtual DbSet<Compras_Detalhes> Compras_Detalhes { get; set; }
        public virtual DbSet<Enderecos> Enderecos { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Municipio> Municipio { get; set; }
        public virtual DbSet<Produtos> Produtos { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<RolesUsuarios> RolesUsuarios { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    }
}
