//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesUsuarios
    {
        public int RoleUsuarioID { get; set; }
        public int IDUsuario { get; set; }
        public short RoleID { get; set; }
    
        public virtual ROLES ROLES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
