//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginMVC2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web.Mvc;
    using System.ComponentModel.DataAnnotations;

    public partial class USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIOS()
        {
            this.Carrinho = new HashSet<Carrinho>();
            this.Compras_Detalhes = new HashSet<Compras_Detalhes>();
            this.Enderecos = new HashSet<Enderecos>();
            this.RolesUsuarios = new HashSet<RolesUsuarios>();
        }

        public int IDUsuario { get; set; }
        public string UserName { get; set; }
        public string Senha { get; set; }
        public string EmailUsuario { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrinho> Carrinho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compras_Detalhes> Compras_Detalhes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enderecos> Enderecos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolesUsuarios> RolesUsuarios { get; set; }
    }

    [MetadataType(typeof(USUARIOSMetadado))]
    public partial class USUARIOS
    {
    }

    public class USUARIOSMetadado
    {
        [DisplayName("Nome de usuário")]
        [Required(ErrorMessage = "Obrigatório informar o nome de usuário")]
        [MaxLength(50), MinLength(6)]
        [TamanhoString(50)]
        public string UserName { get; set; }

        [DisplayName("Senha")]
        [Required]
        [DataType(DataType.Password)]
        public string Senha { get; set; }
    }

    public class Register
    {
        [HiddenInput(DisplayValue = false)]
        [Key]
        public int IDUsuario { get; set; }

        [DisplayName("Nome de usuário")]
        [Required(ErrorMessage = "Obrigatório informar o nome de usuário")]
        [MaxLength(50), MinLength(6)]
        [TamanhoString(50)]
        public string UserName { get; set; }

        [DisplayName("Senha")]
        [Required(ErrorMessage = "Obrigatório informar a senha")]
        [DataType(DataType.Password)]
        public string Senha { get; set; }

        [DisplayName("Confirmar senha")]
        [System.ComponentModel.DataAnnotations.Compare("Senha", ErrorMessage = "As senhas não conferem.")]
        [DataType(DataType.Password)]
        public string ConfirmarSenha { get; set; }

        [DisplayName("E-mail")]
        [TamanhoString(100)]
        [DataType(DataType.EmailAddress, ErrorMessage = "O e-mail inserido não é válido")]
        [Required(ErrorMessage = "Obrigatório informar o e-mail")]
        [MaxLength(50), MinLength(6)]
        public string EmailUsuario { get; set; }
    }
}
